# Generated by Django 6.0.3 on 2026-03-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"verbose_name_plural": "Inventory"},
        ),
    ]
