# Generated by Django 6.0.3 on 2026-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_inventory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
