# Generated by Django 6.0.3 on 2026-03-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_inventory_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
