# Generated by Django 6.0.3 on 2026-03-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_dealer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealer",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
