# Generated by Django 6.0.3 on 2026-03-11 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="dealer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.dealer",
            ),
        ),
    ]
