# Generated by Django 6.0.3 on 2026-03-12 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_alter_order_dealer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="dealer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sales.dealer",
            ),
        ),
    ]
